name: flutter_application_tool_youtube
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  image_gallery_saver_plus: ^4.0.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
